# Generated by Django 5.0.3 on 2024-03-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_blogpost_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
