# Generated by Django 5.0.3 on 2024-04-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_slug_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='town',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='город'),
        ),
    ]
