# Generated by Django 5.0.3 on 2024-04-09 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_creator_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=50)),
                ('version_name', models.CharField(max_length=255)),
                ('is_current_version', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='versions',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current_version', True)), fields=('product',), name='unique_current_version_for_product'),
        ),
    ]
